USE [master]
GO
/****** Object:  Database [PRUEBA_TEV]    Script Date: 8/2/2019 18:11:48 ******/
IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = N'PRUEBA_TEV')
BEGIN
CREATE DATABASE [PRUEBA_TEV]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PRUEBA_TEV', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\PRUEBA_TEV.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PRUEBA_TEV_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\PRUEBA_TEV_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
END
GO
ALTER DATABASE [PRUEBA_TEV] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PRUEBA_TEV].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [PRUEBA_TEV] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [PRUEBA_TEV] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [PRUEBA_TEV] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [PRUEBA_TEV] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [PRUEBA_TEV] SET ARITHABORT OFF 
GO
ALTER DATABASE [PRUEBA_TEV] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [PRUEBA_TEV] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [PRUEBA_TEV] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [PRUEBA_TEV] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [PRUEBA_TEV] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [PRUEBA_TEV] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [PRUEBA_TEV] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [PRUEBA_TEV] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [PRUEBA_TEV] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [PRUEBA_TEV] SET  DISABLE_BROKER 
GO
ALTER DATABASE [PRUEBA_TEV] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [PRUEBA_TEV] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [PRUEBA_TEV] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [PRUEBA_TEV] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [PRUEBA_TEV] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [PRUEBA_TEV] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [PRUEBA_TEV] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [PRUEBA_TEV] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [PRUEBA_TEV] SET  MULTI_USER 
GO
ALTER DATABASE [PRUEBA_TEV] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [PRUEBA_TEV] SET DB_CHAINING OFF 
GO
ALTER DATABASE [PRUEBA_TEV] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [PRUEBA_TEV] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [PRUEBA_TEV] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [PRUEBA_TEV] SET QUERY_STORE = OFF
GO
USE [PRUEBA_TEV]
GO
/****** Object:  Table [dbo].[User]    Script Date: 8/2/2019 18:11:48 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[User]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[User](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](50) NOT NULL,
	[LastName] [varchar](50) NOT NULL,
	[Address] [varchar](50) NOT NULL,
	[CreateDate] [date] NOT NULL,
	[UpdateDate] [date] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO
SET IDENTITY_INSERT [dbo].[User] ON 
GO
INSERT [dbo].[User] ([ID], [Name], [LastName], [Address], [CreateDate], [UpdateDate]) VALUES (1, N'SEBASTIAN', N'ORTIZ SERNA', N'CLL 9SUR 79C - 199', CAST(N'2019-07-31' AS Date), CAST(N'2019-08-02' AS Date))
GO
SET IDENTITY_INSERT [dbo].[User] OFF
GO
USE [master]
GO
ALTER DATABASE [PRUEBA_TEV] SET  READ_WRITE 
GO
